### ISSUE TITLE
Construct Pre vs. Post Plot as a scatter plot (Chris' request)

### ISSUE THREAD

**Issue by firasm** [firasm/interCLASS#2]

**Comment by firasm** [comment]
Here's the plot for Sci 1 Pre and at T2...
![unknown](https://cloud.githubusercontent.com/assets/2507459/8339750/b407de6e-1a6e-11e5-9564-aa5fcbf31c6e.png)

Don't be deceived by the fit or the data - the points are all on top of each other but the line fit is correct. I even verified on Excel

![screen shot 2015-06-24 at 12 45 42 pm](https://cloud.githubusercontent.com/assets/2507459/8339785/fb3b1b7a-1a6e-11e5-80d8-2884a7bab50b.png)

Biol 121 incoming for comparison...

**Comment by firasm** [comment]
Oh my god, I think @chrisaddison was right... this is a pretty awesome way to look at it.

**Comment by firasm** [comment]
Here is Biol 121 WT1:

![biol 121 wt1](https://cloud.githubusercontent.com/assets/2507459/8339928/ead60c76-1a6f-11e5-88ff-60a7c0ce1bcd.png)

**Comment by firasm** [comment]
and Biol 121 WT2

![biol 121 wt2](https://cloud.githubusercontent.com/assets/2507459/8339938/07c01746-1a70-11e5-960f-7f4575640a33.png)

**Comment by firasm** [comment]
We should consider how to interpret the slope...

It means, "Post / Pre" - I think this means that Science One saw a net decrease of -0.14 over the year and Biol 121 saw barely any change at all over a term

P.S. @chrisaddison, @jamescharbonneau you can just reply to these emails and your comments will get added to the issue.

**Comment by chrisaddison** [comment]
I think it will be difficult to take too much from the slopes, but distribution of responses may be interesting.  Can we augment the graphs to include contours/colours (heat map) to indicate the number of responses pre/post.  I think you tried to do that by having the bold stars vs. normal stars, but that might not tell us enough.  If we convert it to percentages (i.e. colour scale, going from 0 to 100% of respondents) would allow us to easily compare BIOL 121 vs. SCIE 001 data.

**Comment by chrisaddison** [comment]
Also, can you try doing a "vector plot", where you plot this same data, but you then draw arrows from the pre-score to the post-score (with an arrow head at the end of the arrow)?  It might be an interesting way to visualize net shifts in responses.

**Comment by firasm** [comment]
So I thought about it a bit more, and I think the best-fit line is a bit of a red-herring. It's difficult to interpret and doesn't really tell us very much. 

I brought back the "Firas' plots" and applied it to this plot as per @jamescharbonneau's suggestion:

![unknown](https://cloud.githubusercontent.com/assets/2507459/8349483/2058a07c-1ad2-11e5-8085-c43a5fad9d56.png)

Now it's very clear what's going on... the green line is the y=x line indicating no-change. So if you just ignore anything lying along the diagonal, you can simply count the number of students above the line or below the line. More students above the line = positive change, and vice versa for the negative change.

**Comment by chrisaddison** [comment]
The Firas plots do make sense now, especially with the green line included.  Would love to see what that looks like for the big classes!

The only thing is that this shows ensemble results/changes.  If we do my requested vector plot, it will give us an idea about individual changes in responses.  (It will look a little messy, but we'll still be looking for trends within the vector plots...)

**Comment by firasm** [comment]
And here are a couple of heat maps (different colour schemes) of the Sci 1 data:

![unknown-2](https://cloud.githubusercontent.com/assets/2507459/8360886/8884d808-1b24-11e5-954d-74f9dc0d44d4.png)
![unknown-3](https://cloud.githubusercontent.com/assets/2507459/8360889/88a1ecae-1b24-11e5-8193-b7dd9f8180cc.png)
![unknown-1](https://cloud.githubusercontent.com/assets/2507459/8360888/889ef7ec-1b24-11e5-855b-94616e09fa2c.png)
![unknown](https://cloud.githubusercontent.com/assets/2507459/8360887/8898dee8-1b24-11e5-8f85-29b27c4f4dd4.png)

**Comment by firasm** [comment]
@chrisaddison: I'll try and tackle the vector plot - just to be clear, you want lines going from the Pre score to the post score, with the arrow-head at the post. I'll do it because I'm curious to see what it will look like, but I predict disaster! 

Perhaps a better way to do it would be (in the case of the Sci 1 plot above) to only have 9 arrows, and the size of the arrowhead/arrow corresponding to the number of people that saw that shift.

**Comment by firasm** [comment]
Here is the bubble plot for Biol 121 WT1 and WT2

![unknown-7](https://cloud.githubusercontent.com/assets/2507459/8350534/5eb0e3bc-1adb-11e5-8184-3b232ce63ed2.png)
![unknown-4](https://cloud.githubusercontent.com/assets/2507459/8350535/5ed15368-1adb-11e5-9e9d-62a206c63296.png)

P.S. I just noticed that the numbers in the Sci 1 plots are percentages of people not raw people. I've changed and included the raw people graph here:

![unknown-6](https://cloud.githubusercontent.com/assets/2507459/8350554/891bceb4-1adb-11e5-9795-d8d951468fbe.png)

**Comment by jamescharbonneau** [comment]
Cool. Try the heat map with a line. 

james

**Comment by firasm** [comment]
Heat maps updated with a line.

**Comment by firasm** [comment]
I'll close the issue now, since we've converged on a visualization.
